language: bash

services: docker

env:
  global:
    - secure: "b0+I3wMQ0WlJOOj037u7f18VcoQIidq+Ue57gGjWiuRxnHcGQVHovaeooF1xm8o4s01ds1dfQyaVGthP4yzHmYI3bGQxQ7SvJeKeTjtnBpkfvlAQd7Kxl6ouaggHLi2xNuvs/aLP3vZubNlBd4kuKViqt53cxHGHXd25r7XIg/V4x04ogZbf6yJCU3QP6tJbX9sORe6e2rvt/63EKNR4Lg1iPCxQTo3JZeuH6PAwy9oE0p2MwsfBUT3VE5E5hlyDGMlWAxedbgmUdEwjxN0Cxchl4JxiNaQodP2qyzPFVeXlidgukHR9+6I4U6hYgHXArreZ9ylYdI/mnzVxcwz11zsEiRz0oqhnGq7mCvYO+BfhygvlJhsGY0VR17UOIZJPmmXsaHwUHWo9LWNJvKqMAElCvrgq+anU7gQeybEAA5RjA+Y1MiGWwLpR+bqd0yFdodiCE5lr+7QTf73rqc7FNkIAkkyPqqw8bsKEz179d1Vs6O+zczyhf6cmaB9l/LD5n2TT1sa8g1WRoLJLjfuyCwqkRpWeyAZmKjvVkMptp7oJGXMB3dfVD2HZsNkpQ2bv6tx16UH901cp3EimN0Xcq8BafisxCMgAG7eHPwM9XGKBFASCE/186q81AG3Aq5LjxZV7KOwtVSD+xl2zEaipJSgEV9S56ZPl+aSezhg0XA8="
    - secure: "Kft1Lhmp9zLiyTEadWzLjyRLU+az5/jZSVeKKz69+Buxi579kuaPTcQvPWTkS5YB141xMuKH/iOuQYsgQuYyfL3t0AussHE2Of5kcBUqQ2VqHNtdDmFOfphhnv/5x04TdmcPPjR9gVct/yS335SSXgd7+GKpNzz/BurWElcZ3ikGjl1hv68MylPzj+LAxLDg/otWtUTrwslaTl+K2/DQXkDIbwPG7eCAb7WdYEqxYc6KotuAjKCZnseos/Sov84qT4NUNJx/4HKy5rnn+7RiZ7dXfwBos74BGuPqSQDp1D8KpdSzSWbSfk6SLh+q4Lrcu41wtKS0fazpHKokd4o9HWGXZy1n7I1YhGz4eMvbGLSQfDUcidrePqvY06w8pOFC2NYpVetssTeJN1dOc2YSK/CjyrXbMVOvnwoux669GzSOHlkPtBoHaEpeti1//oRoU3ZWEp7OvbHCvLUFbs+JNmBQO+eR9LnvYj3NiPiVkhFf7QdxtCaTx6Uc7o2bCWmZLUPLJbgJETHzg3lw1XEEaijGlij4GATJLvpUoarWnNp98yTFGu7we4NCiPDJmE+7GqQf5CAeg3P5GXOioTmt6dmOs5Q5NsI5Gl5TWi7vPCvyweDaVUpYwDakf6Ybije7XJwgD1CZ97e0LXpKfysCh1FeOKQN6ne8RqatDTrUiD8="
  matrix:
    - VERSION=latest

before_script:
  - cd src/
  - IMAGE_NAME="chesszebra/$(echo "$TRAVIS_REPO_SLUG" | cut -c 25-):${VERSION}"

script:
  - docker build -t "$IMAGE_NAME" .

after_success:
  - docker login --username $DOCKER_USER --password $DOCKER_PASS
  - docker push $IMAGE_NAME

after_script:
  - docker images

notifications:
  email: false
