language: bash

services: docker

env:
  global:
    - secure: "jixPu4rL6yOE1G8lVwPp5ezfVUrQyUln260TmxfiDujrpxlMrxDoMgf03vn1ZnYdF50Bct3Y6a74iuym1c4roMfPc4VeNUh3T+lwTTD9EF/KCwcaC7gzT5gtO9AvMtvgFd9hshPN4P9BVue/JTB142M33/DDg6aYRGnzwABJBvm3Ty3xt6WhUzKx+PiqsF1fgM7n9BP12SI+Xia0gwsLKWi3QrbNCzpPgbgjXJ/GjFcOh4uqNAagdPWgp9aWT50z1QDk3LU7X9d+3Dd+Qc36gZIV87PWUKD8YizsFPndTlCEDV6m9ST94TEz0+4wGd3a3Ar/lKUx2m6+Z/2/8HwQcXUvGgrC0qG9yGzAsvf1y7GVxbNYV2ihnthIHsaXnFagU+DGBTaEH8BIcKuZXBPgDKds0Nl+RlKDpNFqHmfBvRy3vSTRwHJQTWH2WdZfW4ljoW2UNmH24nVCnEBlBTgBEIJGEUWtvJO6kAHQLf4MRiibd3zrB36qM4MPPrgM/tMfSdRkJo70LoyP3ne6+GTjvAGjRMaXAejjU5QD41BeO9Wwd8+/AiCgarE6tkgTS9d9sUmEZ9p2Y5xw8ae8YbnHrMo9Ulwk8Zzy8TP0g9n/b1paQ+QMiKTGixWoTeR6D3QAmKZ9PDVKyaVxjlCXOuT9g5qzOsD2gZHQpZmPlJqSMkU="
    - secure: "vTCqaoDf6O9986FeBXUvrb7SBN6Tr4XVt8idFD1ZvX8Uqo5mlZ0oZJ6a/tcH4E5IVV7VPEUnrEGZQch8rfnHbWJbkVh9IozpX+VIGwnVXTBIWihmvTcePUwvwxd2y4EducR6YQKFRsDnR5TlaQ7fx90JeAKtvdhFGrvrIPDBtWCCOx7H+coa8pWlp6lEhM3w0ewaM3zR4GKrU8NSvcBydh1suycKCbx714z4XI07BKuKPMKWvHxtN67kJMi97l9JzjQANYYt21SQOHX2S3CU/YmSnN8qwiza1Mw1cPsCwmhwC26mcd0uoJG2qlcdVbvM0vETvyb1i3ZYMLbjdzZLI2TCLHO6qp4pnpYCQyIktsbktoPDQyIbtPA86zWtU726S8jrxVAHs8zS4/Lxyw8cNw2Falg7nq36My4w60SIcTl/xGkxt6nkylSJp8gUcqBJSxwNpZ3Bg61QGoayzpqFJdmPoAAgQgLHgrmEq82ga9c4afTqUtskUA+/pPVmXYNLmzc6RveT0Q+OAffQVHmW3lzJhBKbBIbfHuZBTVB/P5lK2G150psH4WLIhYfbhJ78w5OvCejVKubjQ4HgjSttm8JKYWe8isXwyF8qyMiXsLAXRykjFR75raj4At2T2AZIQCLkLMZzA621zvPm3zCdawHlYqtKHjAFIyuV+M+NpQE="
  matrix:
    - VERSION=latest

before_script:
  - cd src/
  - IMAGE_NAME="chesszebra/$(echo "$TRAVIS_REPO_SLUG" | cut -c 25-):${VERSION}"

script:
  - docker build -t "$IMAGE_NAME" .

after_success:
  - docker login --username $DOCKER_USER --password $DOCKER_PASS
  - docker push $IMAGE_NAME

after_script:
  - docker images

notifications:
  email: false
